# Generated by Django 2.1.4 on 2019-01-01 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 1, 22, 16, 9, 929867), verbose_name='添加时间'),
        ),
    ]
