# Generated by Django 2.1.4 on 2019-01-05 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190101_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 5, 20, 41, 33, 546899), verbose_name='添加时间'),
        ),
    ]
